hetic_app:
    resource: "@HETICAppBundle/Resources/config/routing.yml"
    prefix:   /

hetic_core:
    resource: "@HETICCoreBundle/Resources/config/routing.yml"
    prefix:   /core

hetic_user:
    resource: "@HETICUserBundle/Resources/config/routing.yml"
    prefix:   /account
