<?php

namespace HETIC\CoreBundle\Repository;

/**
 * AdressesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressesTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
