<?php

namespace HETIC\CoreBundle\Repository;

/**
 * CommandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandsRepository extends \Doctrine\ORM\EntityRepository
{
}
