<?php

namespace HETIC\CoreBundle\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductsofTheDay($date) {
        $qb = $this->createQueryBuilder('p');

        return $qb->Where('p.expirationDate < :date')
                  ->setParameter('date', $date)
                  ->getQuery()
                  ->getResult()
                  ;
    }
}
