<?php

namespace HETIC\CoreBundle\Repository;

/**
 * QuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
