<?php

namespace HETIC\CoreBundle\Repository;

/**
 * WarehouseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarehouseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
